### ISSUE TITLE
Taro版本有开源吗？

### ISSUE THREAD

**Issue by DreamPWJ** [oceanengine/okeedesign-mobile-react#2]
现在组件数量还是太少， 维护感觉不是很活跃啊

**Comment by ybbdaidai** [comment]
Taro 版本短期内还不打算开源，原因是完成度没有 Vue、React 版本高，还需要完善一段时间。

**Comment by ybbdaidai** [comment]
1. 现有的组件数量，其实已经能够满足内部需求了，所以希望通过开源能够获取到更多有价值的需求。
2. 把组件做好，其实是一件比较费时费力的事，所以也希望通过开源吸引感兴趣的同学加入我们。
3. 我们也会继续努力，把活跃度，组件数量、组件质量进一步提升。

**Comment by DreamPWJ** [comment]
> Taro 版本短期内还不打算开源，原因是完成度没有 Vue、React 版本高，还需要完善一段时间。

Taro版本用的Vue语法还是React语法？
